Exercise 1

In [6]:
import numpy as np

l = [i for i in range(1,26)]
print(l)
a = np.array(l)
print(a)
reshape = a.reshape(5,5)
print(reshape)

print(reshape[2][3])
print(reshape[2,3])
print(reshape[2])
print(reshape[0:2])
print(reshape[0:2:2])
print(reshape[::-2])
print(reshape[1:3,1:3])
print(reshape[3::3])
print(reshape[::-1])

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25]
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
14
14
[11 12 13 14 15]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3 4 5]]
[[21 22 23 24 25]
 [11 12 13 14 15]
 [ 1  2  3  4  5]]
[[ 7  8]
 [12 13]]
[[16 17 18 19 20]]
[[21 22 23 24 25]
 [16 17 18 19 20]
 [11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
