goes from rows index to columns index

In [ ]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print(a[2,2])
print(a[1][1])

In [1]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
arrs = arr[0:3]
print(arrs)
arrs[:] = 2
print(arrs)
print(arr)

[1 2 3 4 5]
[1 2 3]
[2 2 2]
[2 2 2 4 5]
